#pragma once

#define HBRIDGE_IN1_PIN 12
#define HBRIDGE_IN2_PIN 13
#define HBRIDGE_IN3_PIN 27
#define HBRIDGE_IN4_PIN 26
#define HBRIDGE_EN1_PIN 25
#define HBRIDGE_EN2_PIN 33

#define RIGHT_MOTOR_FORWARD_PIN HBRIDGE_IN2_PIN
#define RIGHT_MOTOR_REVERSE_PIN HBRIDGE_IN1_PIN
#define RIGHT_MOTOR_EN_PIN HBRIDGE_EN1_PIN
#define RIGHT_MOTOR_PWM_CHANNEL 0  // only for esp32

#define LEFT_MOTOR_FORWARD_PIN HBRIDGE_IN3_PIN
#define LEFT_MOTOR_REVERSE_PIN HBRIDGE_IN4_PIN
#define LEFT_MOTOR_EN_PIN HBRIDGE_EN2_PIN
#define LEFT_MOTOR_PWM_CHANNEL 1  // only for esp32
